// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHltD1o8AYQ5lWHFrUwAmGKhdI0LS9mTk',
    appId: '1:866427811004:android:4a47a48a1963b04ae48cb9',
    messagingSenderId: '866427811004',
    projectId: 'music-shorts',
    databaseURL: 'https://music-shorts-default-rtdb.firebaseio.com',
    storageBucket: 'music-shorts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ1wPgoEj0JG3nNJcwGSbmGuDBIHN_Cik',
    appId: '1:866427811004:ios:7c0b25bca77e45b0e48cb9',
    messagingSenderId: '866427811004',
    projectId: 'music-shorts',
    databaseURL: 'https://music-shorts-default-rtdb.firebaseio.com',
    storageBucket: 'music-shorts.appspot.com',
    iosClientId:
        '866427811004-0n642qupjqslsei42oaao0v42ob58m6q.apps.googleusercontent.com',
    iosBundleId: 'com.hardcorestudygroup.musicshorts',
  );
}
