openapi: '3.0.0'
info:
  version: 0.0.1
  title: Music shorts
  description: Music shorts app & admin api docs
  license:
    name: GLP 3.0
    identifier: GLP 3.0
    url: https://github.com/hardcore-study-group/music-shorts/blob/main/LICENSE
servers:
  - url: https://us-central1-music-shorts.cloudfunctions.net/api
  - url: http://0.0.0.0:5000/music-shorts/us-central1/api
paths:
  /auth/token/swap:
    $ref: './auth.yaml#/~1auth~1token~1swap'
  /auth/token/refresh:
    $ref: './auth.yaml#/~1auth~1token~1refresh'
  /me:
    $ref: './me.yaml#/~1me'
  /me/playlist/tracks:
    $ref: './me.yaml#/~1me~1playlist~1tracks'
  /me/playlist/tracks/{id}:
    $ref: './me.yaml#/~1me~1playlist~1tracks~1{id}'
  /search/spotify:
    $ref: './search.yaml#/~1search~1spotify'
  /search/youtube:
    $ref: './search.yaml#/~1search~1youtube'
  /tracks:
    $ref: './tracks.yaml#/~1tracks'
  /tracks/{id}:
    $ref: './tracks.yaml#/~1tracks~1{id}'
  /tracks/recommendation:
    $ref: './tracks.yaml#/~1tracks~1recommendation'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
    AdminPassword:
      type: http
      scheme: bearer
  responses:
    successResponse:
      description: successful request
      content:
        application/json:
          schema:
            type: object
